apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-webapp-deployment
  labels:
    app: simpleapp-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp-webapp
  template:
    metadata:
      labels:
        app: simpleapp-webapp
    spec:
      initContainers:
        - name: install
          image: busybox:1.28
          command:
            - wget
            - "-O"
            - "/work-dir/index.html"
            - http://info.cern.ch
          volumeMounts:
            - name: workdir
              mountPath: "/work-dir"
      containers:
        - name: simpleapp-container
          image: ajinkyap009/cloudethix_initcontainer_ajinkya:v1
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: workdir
          emptyDir: {}
